'use strict';
const http = require('node:http');
const crypto = require('node:crypto');

const MAX_BODY = 64 * 1024;
const ALLOWED = new Set([
  'tabs.create','tabs.query','tabs.update','tabs.remove',
  'windows.create','windows.getAll','windows.getLastFocused','windows.getCurrent','windows.update','windows.remove',
  'notifications.create','notifications.clear',
  'cookies.get','cookies.getAll','cookies.set','cookies.remove',
  'identity.launchWebAuthFlow',
  'sidePanel.open','sidePanel.setOptions'
]);

let server = null;
let port = 0;
let dispatcher = null;
const contexts = new Map();

function json(res, status, body){
  res.writeHead(status, {
    'content-type':'application/json; charset=utf-8',
    'access-control-allow-origin':'*',
    'cache-control':'no-store',
    'x-content-type-options':'nosniff'
  });
  res.end(JSON.stringify(body));
}
function readBody(req){
  return new Promise((resolve,reject)=>{
    let size=0, chunks=[];
    req.on('data', chunk => {
      size += chunk.length;
      if(size > MAX_BODY){ reject(new Error('bridge request too large')); req.destroy(); return; }
      chunks.push(chunk);
    });
    req.on('end',()=>resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error',reject);
  });
}
async function handle(req,res){
  if(req.method==='OPTIONS'){
    res.writeHead(204,{
      'access-control-allow-origin':'*',
      'access-control-allow-methods':'POST, OPTIONS',
      'access-control-allow-headers':'content-type',
      'cache-control':'no-store'
    });
    res.end(); return;
  }
  if(req.method!=='POST' || req.url!=='/rpc') return json(res,404,{error:'not found'});
  let payload;
  try { payload=JSON.parse(await readBody(req)); }
  catch(err){ return json(res,400,{error:String(err.message||err)}); }
  const token=String(payload?.token||'');
  const context=contexts.get(token);
  if(!context) return json(res,403,{error:'invalid bridge token'});
  const method=String(payload?.method||'');
  if(!ALLOWED.has(method)) return json(res,403,{error:'bridge method is not allowed'});
  if(typeof dispatcher!=='function') return json(res,503,{error:'bridge host is not ready'});
  try{
    const value=await dispatcher(context,method,payload?.args);
    return json(res,200,{ok:true,value:value===undefined?null:value});
  }catch(err){
    return json(res,500,{ok:false,error:String(err?.message||err)});
  }
}
async function init(dispatch){
  if(server){ if(dispatch) dispatcher=dispatch; return {port,endpoint:`http://127.0.0.1:${port}/rpc`}; }
  dispatcher=dispatch||null;
  server=http.createServer((req,res)=>{ handle(req,res).catch(err=>json(res,500,{error:String(err?.message||err)})); });
  await new Promise((resolve,reject)=>{
    server.once('error',reject);
    server.listen(0,'127.0.0.1',()=>{ server.off('error',reject); resolve(); });
  });
  port=Number(server.address()?.port||0);
  return {port,endpoint:`http://127.0.0.1:${port}/rpc`};
}
function setDispatcher(dispatch){ dispatcher=dispatch||null; }
function issueContext(context={}){
  if(!server||!port) throw new Error('extension bridge has not been initialized');
  const token=crypto.randomBytes(32).toString('hex');
  contexts.set(token,context);
  return { token, endpoint:`http://127.0.0.1:${port}/rpc` };
}
function revoke(token){ contexts.delete(String(token||'')); }
async function close(){
  contexts.clear();
  dispatcher=null;
  if(!server){ port=0; return; }
  const closing=server; server=null; port=0;
  await new Promise(resolve=>closing.close(()=>resolve()));
}

function workerBootstrap({endpoint,token,originalWorker}){
  if(!/^http:\/\/127\.0\.0\.1:\d+\/rpc$/.test(String(endpoint||''))) throw new Error('invalid bridge endpoint');
  if(!/^[a-f0-9]{64}$/.test(String(token||''))) throw new Error('invalid bridge token');
  const original=String(originalWorker||'');
  if(!original || original.includes('..') || /^[a-z][a-z0-9+.-]*:/i.test(original)) throw new Error('invalid original worker path');
  return `/* Generated by Breeze. This file wraps the extension's original MV3 service worker\n   and fills browser-host APIs that Electron does not natively expose. */\n'use strict';\nconst __BREEZE_ENDPOINT=${JSON.stringify(endpoint)};\nconst __BREEZE_TOKEN=${JSON.stringify(token)};\nasync function __breezeRpc(method,args){\n  const response=await fetch(__BREEZE_ENDPOINT,{method:'POST',headers:{'content-type':'text/plain;charset=UTF-8'},body:JSON.stringify({token:__BREEZE_TOKEN,method,args})});\n  let body={}; try{body=await response.json();}catch{}\n  if(!response.ok||body.ok===false) throw new Error(body.error||('Breeze extension bridge HTTP '+response.status));\n  return body.value;\n}\nfunction __dual(method,args,cb){\n  const p=__breezeRpc(method,args);\n  if(typeof cb==='function') p.then(v=>cb(v),()=>cb());\n  return p;\n}\nfunction __root(name){ if(!chrome[name]){ try{ chrome[name]={}; }catch{} } return chrome[name]; }\nconst __tabs=__root('tabs');\n__tabs.create=(details,cb)=>__dual('tabs.create',details||{},cb);\n__tabs.query=(queryInfo,cb)=>__dual('tabs.query',queryInfo||{},cb);\n__tabs.update=(tabId,props,cb)=>{ if(typeof tabId==='object'){cb=props;props=tabId;tabId=null;} return __dual('tabs.update',{tabId,props:props||{}},cb); };\n__tabs.remove=(tabIds,cb)=>__dual('tabs.remove',{tabIds},cb);\nconst __windows=__root('windows');\n__windows.create=(details,cb)=>__dual('windows.create',details||{},cb);\n__windows.getAll=(getInfo,cb)=>{ if(typeof getInfo==='function'){cb=getInfo;getInfo={};} return __dual('windows.getAll',getInfo||{},cb); };\n__windows.getLastFocused=(getInfo,cb)=>{ if(typeof getInfo==='function'){cb=getInfo;getInfo={};} return __dual('windows.getLastFocused',getInfo||{},cb); };\n__windows.getCurrent=(getInfo,cb)=>{ if(typeof getInfo==='function'){cb=getInfo;getInfo={};} return __dual('windows.getCurrent',getInfo||{},cb); };\n__windows.update=(windowId,updateInfo,cb)=>__dual('windows.update',{windowId,updateInfo:updateInfo||{}},cb);\n__windows.remove=(windowId,cb)=>__dual('windows.remove',{windowId},cb);\nconst __notifications=__root('notifications');\n__notifications.create=(id,options,cb)=>{ if(typeof id==='object'){cb=options;options=id;id='';} return __dual('notifications.create',{id,options:options||{}},cb); };\n__notifications.clear=(id,cb)=>__dual('notifications.clear',{id},cb);\nconst __cookies=__root('cookies');\n__cookies.get=(details,cb)=>__dual('cookies.get',details||{},cb);\n__cookies.getAll=(details,cb)=>__dual('cookies.getAll',details||{},cb);\n__cookies.set=(details,cb)=>__dual('cookies.set',details||{},cb);\n__cookies.remove=(details,cb)=>__dual('cookies.remove',details||{},cb);\nconst __commands=__root('commands');\n__commands.getAll=(cb)=>{ const commands=chrome.runtime.getManifest().commands||{}; const rows=Object.entries(commands).map(([name,v])=>({name,description:v&&v.description||'',shortcut:v&&v.suggested_key&&(v.suggested_key.default||v.suggested_key.windows||v.suggested_key.mac)||''})); if(typeof cb==='function') queueMicrotask(()=>cb(rows)); return Promise.resolve(rows); };\nconst __identity=__root('identity');\n__identity.getRedirectURL=(path='')=>'https://'+chrome.runtime.id+'.chromiumapp.org/'+String(path||'').replace(/^\\/+/, '');\n__identity.launchWebAuthFlow=(details,cb)=>__dual('identity.launchWebAuthFlow',details||{},cb);\nconst __sidePanel=__root('sidePanel');\n__sidePanel.open=(options,cb)=>__dual('sidePanel.open',options||{},cb);\n__sidePanel.setOptions=(options,cb)=>__dual('sidePanel.setOptions',options||{},cb);\nimportScripts(chrome.runtime.getURL(${JSON.stringify(original)}));\n`;
}

module.exports={init,setDispatcher,issueContext,revoke,close,workerBootstrap,ALLOWED};
