const API=window.__BREEZE_PDF__; const qs=new URLSearchParams(location.search); const token=qs.get('token')||'';
const $=s=>document.querySelector(s); const body=document.body;
let pdf=null,page=1,scale=1,textSize=20,line=1.72,wide=false,focus=false; const textCache=new Map(); let renderSeq=0;
function fmtBytes(n){if(!Number.isFinite(n))return ''; const u=['B','KB','MB','GB']; let i=0,v=n; while(v>=1024&&i<u.length-1){v/=1024;i++;} return `${v.toFixed(i?1:0)} ${u[i]}`;}
function status(msg,bad=false){const e=$('#toolStatus');e.textContent=msg;e.classList.add('show');e.style.color=bad?'#9b1c1c':'';clearTimeout(status.t);status.t=setTimeout(()=>e.classList.remove('show'),5000);}
async function boot(){
  if(!API||!token)return fatal('Breeze could not open the local document bridge.');
  try{
    const [{default:unused,...pdfjs},load]=await Promise.all([import('../node_modules/pdfjs-dist/build/pdf.mjs'),API.load(token)]);
    if(load?.error)throw new Error(load.error); const data=load.data||load;
    pdfjs.GlobalWorkerOptions.workerSrc=new URL('../node_modules/pdfjs-dist/build/pdf.worker.mjs',import.meta.url).href;
    pdf=await pdfjs.getDocument({data:new Uint8Array(data),enableScripting:false,isEvalSupported:false,stopEventLoop:true}).promise;
    const info=await API.info(token); paintInfo(info); $('#pageCount').textContent=`/ ${pdf.numPages}`; $('#pageNo').max=pdf.numPages;
    await renderPage(); buildThumbs();
  }catch(e){fatal(String(e?.message||e));}
}
function fatal(msg){$('#stage').innerHTML=`<div class="fatal"><b>Could not open this PDF.</b><br><br>${escapeHtml(msg)}</div>`;}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function paintInfo(info={}){$('#fileName').textContent=info.fileName||'Local PDF'; $('#metaLine').textContent=`${info.pageCount||'—'} pages · ${fmtBytes(info.fileSize)}`; const rows=[['Title',info.title],['Author',info.author],['Pages',info.pageCount],['Size',fmtBytes(info.fileSize)],['Created',info.createdAt?new Date(info.createdAt).toLocaleDateString():null]].filter(r=>r[1]); $('#docMeta').replaceChildren(...rows.map(([k,v])=>{const d=document.createElement('div');d.innerHTML=`<b>${escapeHtml(k)}</b> · ${escapeHtml(v)}`;return d;}));}
async function renderPage(){if(!pdf)return; const seq=++renderSeq; $('#rendering').classList.add('on'); try{const pg=await pdf.getPage(page); if(seq!==renderSeq)return; const viewport=pg.getViewport({scale}); const c=$('#pdfCanvas'),ctx=c.getContext('2d',{alpha:false}); const ratio=Math.min(devicePixelRatio||1,2); c.width=Math.floor(viewport.width*ratio);c.height=Math.floor(viewport.height*ratio);c.style.width=`${viewport.width}px`;c.style.height=`${viewport.height}px`; await pg.render({canvasContext:ctx,viewport,transform:ratio!==1?[ratio,0,0,ratio,0,0]:null,background:'#ffffff'}).promise; $('#pageNo').value=page; $('#zoomLabel').textContent=Math.round(scale*100)+'%'; markThumb(); if(body.dataset.mode==='comfort')renderComfort();}finally{$('#rendering').classList.remove('on');}}
async function fitWidth(){if(!pdf)return; const pg=await pdf.getPage(page),base=pg.getViewport({scale:1}); const avail=Math.max(260,$('#stage').clientWidth-84); scale=Math.max(.35,Math.min(3,avail/base.width)); renderPage();}
async function pageText(n){if(textCache.has(n))return textCache.get(n); const pg=await pdf.getPage(n),tc=await pg.getTextContent({includeMarkedContent:false}); const pars=[];let line=''; for(const it of tc.items){if(!('str'in it))continue; const s=String(it.str||'').trim(); if(s)line+=(line?' ':'')+s; if(it.hasEOL&&line){pars.push(line);line='';}} if(line)pars.push(line); const compact=pars.filter(Boolean); textCache.set(n,compact); return compact;}
async function renderComfort(){const box=$('#reflowText');box.textContent='Extracting readable text…'; const pars=await pageText(page); box.replaceChildren(); if(!pars.length){box.textContent='No selectable text was found on this page. This may be a scanned image; use Page mode for the exact document.';return;} pars.forEach((p,i)=>{const el=document.createElement('p');el.textContent=p;el.tabIndex=0;el.onclick=()=>focusParagraph(el);el.onfocus=()=>focusParagraph(el);if(i===0&&focus)el.classList.add('focused');box.append(el);}); applyComfort();}
function applyComfort(){const box=$('#reflowText');box.style.setProperty('--fs',textSize+'px');box.style.setProperty('--lh',line);box.style.setProperty('--measure',wide?'840px':'690px');box.classList.toggle('focusMode',focus); if(focus&&!box.querySelector('.focused'))box.querySelector('p')?.classList.add('focused');}
function focusParagraph(el){if(!focus)return; $$('#reflowText p').forEach(p=>p.classList.toggle('focused',p===el)); el.scrollIntoView({block:'center',behavior:'smooth'});}
function $$(s){return [...document.querySelectorAll(s)];}
async function buildThumbs(){const box=$('#thumbs');box.replaceChildren(); const max=Math.min(pdf.numPages,120); for(let n=1;n<=max;n++){const b=document.createElement('button');b.className='thumb';b.dataset.page=n;const c=document.createElement('canvas'),sp=document.createElement('span');sp.textContent=n;b.append(c,sp);b.onclick=()=>go(n);box.append(b); (async()=>{try{const pg=await pdf.getPage(n),vp=pg.getViewport({scale:.16}),ctx=c.getContext('2d',{alpha:false});c.width=Math.max(1,Math.floor(vp.width));c.height=Math.max(1,Math.floor(vp.height));await pg.render({canvasContext:ctx,viewport:vp,background:'#fff'}).promise;}catch{}})();} if(pdf.numPages>max){const d=document.createElement('div');d.style.cssText='font-size:9px;color:var(--muted);text-align:center;padding:8px';d.textContent=`+ ${pdf.numPages-max} more pages`;box.append(d);} markThumb();}
function markThumb(){$$('.thumb').forEach(b=>b.classList.toggle('active',Number(b.dataset.page)===page)); const active=$(`.thumb[data-page="${page}"]`);active?.scrollIntoView({block:'nearest'});}
function go(n){const v=Math.max(1,Math.min(pdf?.numPages||1,Number(n)||1)); if(v===page)return; page=v;renderPage();}
async function search(dir=1){const q=$('#searchInput').value.trim().toLowerCase();if(!q||!pdf)return; $('#searchStatus').textContent='Searching…'; for(let step=1;step<=pdf.numPages;step++){let n=((page-1+dir*step)%pdf.numPages+pdf.numPages)%pdf.numPages+1;const text=(await pageText(n)).join(' ').toLowerCase();if(text.includes(q)){page=n;$('#searchStatus').textContent=`Page ${n}`;await renderPage();return;}} $('#searchStatus').textContent='No matches';}
function setMode(mode){body.dataset.mode=mode;$('#pageMode').classList.toggle('active',mode==='page');$('#comfortMode').classList.toggle('active',mode==='comfort'); if(mode==='comfort')renderComfort();}
$('#prev').onclick=()=>go(page-1);$('#next').onclick=()=>go(page+1);$('#pageNo').onchange=e=>go(e.target.value);$('#zoomOut').onclick=()=>{scale=Math.max(.35,scale-.1);renderPage();};$('#zoomIn').onclick=()=>{scale=Math.min(3,scale+.1);renderPage();};$('#fit').onclick=fitWidth;$('#pageMode').onclick=()=>setMode('page');$('#comfortMode').onclick=()=>setMode('comfort');
$('#findBtn').onclick=()=>{$('#searchbar').classList.add('open');$('#searchInput').focus();};$('#searchClose').onclick=()=>$('#searchbar').classList.remove('open');$('#searchNext').onclick=()=>search(1);$('#searchPrev').onclick=()=>search(-1);$('#searchInput').onkeydown=e=>{if(e.key==='Enter')search(e.shiftKey?-1:1);if(e.key==='Escape')$('#searchbar').classList.remove('open');};
$('#toolsBtn').onclick=()=>body.classList.toggle('toolsOpen');$('#toolsClose').onclick=()=>body.classList.remove('toolsOpen');$('#textMinus').onclick=()=>{textSize=Math.max(15,textSize-1);applyComfort();};$('#textPlus').onclick=()=>{textSize=Math.min(34,textSize+1);applyComfort();};$('#lineBtn').onclick=()=>{line=line>=1.9?1.55:line+.15;applyComfort();};$('#widthBtn').onclick=()=>{wide=!wide;applyComfort();};$('#focusBtn').onclick=()=>{focus=!focus;$('#focusBtn').classList.toggle('active',focus);applyComfort();};$('#theme').onchange=e=>body.dataset.theme=e.target.value;
$$('[data-action]').forEach(b=>b.onclick=async()=>{const a=b.dataset.action,pages=$('#pageSpec').value.trim(),ranges=$('#splitSpec').value.trim();b.disabled=true;status('Working locally…');try{let r;if(a==='extract')r=await API.extract(token,pages);else if(a.startsWith('rotate'))r=await API.rotate(token,pages,Number(a.replace('rotate','')));else if(a==='split')r=await API.split(token,ranges);else if(a==='merge')r=await API.merge(token); if(r?.error)throw new Error(r.error);if(r?.canceled)status('Canceled');else status(r?.files?`Created ${r.files.length} files`:`Saved ${r?.fileName||'PDF'}`);}catch(e){status(String(e?.message||e),true);}finally{b.disabled=false;}});
addEventListener('keydown',e=>{const mod=e.metaKey||e.ctrlKey;if(mod&&e.key.toLowerCase()==='f'){e.preventDefault();$('#searchbar').classList.add('open');$('#searchInput').focus();}if(e.key==='PageDown'||e.key==='ArrowRight')go(page+1);if(e.key==='PageUp'||e.key==='ArrowLeft')go(page-1);if(mod&&(e.key==='+'||e.key==='=')){e.preventDefault();scale=Math.min(3,scale+.1);renderPage();}if(mod&&e.key==='-'){e.preventDefault();scale=Math.max(.35,scale-.1);renderPage();}});
boot();
